spring:
  application:
    name: vca

  datasource:
    url: jdbc:postgresql://localhost:5432/veriMediaDb
    username: user
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}

app:
  storage:
    dir: ${STORAGE_DIR:./storage}